linters:
    enable-all: true
    disable:
        - nlreturn
        - varnamelen
        - wsl
        - perfsprint
        - depguard
        - forbidigo
        - exhaustruct
        - tenv

linters-settings:
    gci:
        sections:
            - standard # Standard lib
            - default # External dependencies
            - prefix(github.com/bjlag/go-keeper) # Internal packages